spring:
  cloud:
    gateway:
      routes:
        - id: example_route
          uri: http://127.0.0.1:8085
          predicates:
            - Path=/api/**
          #filters:
           # - RewritePath=/menu/list, /api/menu/list
logging:
  level:
    org.springframework.cloud.gateway: DEBUG  # Enable detailed logging for Spring Cloud Gateway
    org.springframework.web: DEBUG  # Enable detailed logging for HTTP requests/responses
    root: INFO  # Default log level
server:
  port: 8095